# CS 224N: Assignment 1

In [1]:
# Setup code
import numpy as np
import matplotlib.pyplot as plt

## 1. Softmax (10 points)

### (b) Implement softmax

In [2]:
%run q1_softmax.py

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!

Running your tests...


## 2. Neural Network Basics (30 points)

### (e) Implement sigmoid

In [3]:
%run q2_sigmoid.py

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results by hand!

Running your tests...


### (f) Gradient check

In [4]:
%run q2_gradcheck.py

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!

Running your sanity checks...


### (g). Implement the forward and backward passes for a neural network

In [5]:
%run q2_neural.py

Running sanity check...
Gradient check failed.
First gradient error found at index (0,)
Your gradient: -0.253772 	 Numerical gradient: 0.253772
Running your sanity checks...


## 3. word2vec (40 points + 2 bonus)

### (e). Implement the word2vec models

In [6]:
%run q3_word2vec.py

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]

==== Gradient check for skip-gram ====
Gradient check passed!
Gradient check passed!

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(11.166108785061258, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-1.26947336, -1.36873024,  2.45159048],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.4104582 ,  0.18835042,  1.4327257 ],
       [ 0.38202654, -0.17530374, -1.33348351],
       [ 0.07009331, -0.03216431, -0.24466434],
       [ 0.09472137, -0.0434656 , -0.33062989],
       [-0.13638302,  0.06258323,  0.47605203]]))
(14.093692923613229, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-3.86801854, -1.1271281 , -1.5266772 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.  

### (f). SGD optimizer

In [7]:
%run q3_sgd.py

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.414836786079764e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.524451035823933e-09

Running your sanity checks...


### (g). Use the Stanford Sentiment Treebank (SST) dataset to train word vectors

In [8]:
%run q3_run.py

d:\Anaconda3\lib\site-packages\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


iter 100: 19.824039
iter 200: 19.885036
iter 300: 20.049740
iter 400: 20.168080
iter 500: 20.188994
iter 600: 20.437639
iter 700: 20.399295
iter 800: 20.561096
iter 900: 20.493754
iter 1000: 20.536539
iter 1100: 20.554214
iter 1200: 20.578520
iter 1300: 20.563415
iter 1400: 20.525984
iter 1500: 20.452432
iter 1600: 20.572657
iter 1700: 20.519374
iter 1800: 20.536106
iter 1900: 20.545065
iter 2000: 20.682110
iter 2100: 20.776750
iter 2200: 20.767022
iter 2300: 20.842519
iter 2400: 20.997134
iter 2500: 21.175011
iter 2600: 21.176830
iter 2700: 21.216225
iter 2800: 21.207287
iter 2900: 21.287716
iter 3000: 21.231135
iter 3100: 21.076748
iter 3200: 21.036459
iter 3300: 20.883766
iter 3400: 20.722535
iter 3500: 20.819453
iter 3600: 20.688059
iter 3700: 20.614748
iter 3800: 20.641461
iter 3900: 20.608486
iter 4000: 20.575084
iter 4100: 20.362752
iter 4200: 20.309977
iter 4300: 20.205327
iter 4400: 20.085116
iter 4500: 19.967595
iter 4600: 19.860409
iter 4700: 19.798612
iter 4800: 19.687301
i

## 4. Sentiment Analysis (20 points)
Note: This part is done with Python 2.

In [2]:
%run q4_sentiment.py --pretrained

d:\Anaconda3\envs\python2\lib\site-packages\matplotlib\__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


Training for reg=0.000000
Train accuracy (%): 39.922753
Dev accuracy (%): 36.330609
Test accuracy (%): 36.968326
Training for reg=0.000000
Train accuracy (%): 39.934457
Dev accuracy (%): 36.330609
Test accuracy (%): 36.968326
Training for reg=0.000000
Train accuracy (%): 39.911049
Dev accuracy (%): 36.603088
Test accuracy (%): 37.058824
Training for reg=0.000000
Train accuracy (%): 39.957865
Dev accuracy (%): 36.512262
Test accuracy (%): 36.968326
Training for reg=0.000000
Train accuracy (%): 39.922753
Dev accuracy (%): 36.330609
Test accuracy (%): 36.968326
Training for reg=0.000006
Train accuracy (%): 39.899345
Dev accuracy (%): 36.603088
Test accuracy (%): 37.058824
Training for reg=0.000098
Train accuracy (%): 39.922753
Dev accuracy (%): 36.603088
Test accuracy (%): 37.058824
Training for reg=0.004041
Train accuracy (%): 39.946161
Dev accuracy (%): 36.330609
Test accuracy (%): 37.058824
Training for reg=0.068435
Train accuracy (%): 39.875936
Dev accuracy (%): 36.330609
Test accurac

In [2]:
# Note: Error due to previouly dumping the parameters with pickle protocol 3 in Python 3. This part is incomplete.
%run q4_sentiment.py --yourvectors

d:\Anaconda3\envs\python2\lib\site-packages\matplotlib\__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


ValueError: unsupported pickle protocol: 3