# CS 224N: Assignment 1

In [1]:
# Setup code
import numpy as np
import matplotlib.pyplot as plt

## 1. Softmax (10 points)

### (b) Implement softmax

In [2]:
from q1_softmax import softmax, test_softmax_basic
# Running basic tests
test_softmax_basic()

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!



## 2. Neural Network Basics (30 points)

### (e) Implement sigmoid

In [3]:
from q2_sigmoid import sigmoid, sigmoid_grad, test_sigmoid_basic
# Running basic tests
test_sigmoid_basic()

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results by hand!



### (f) Gradient check

In [4]:
from q2_gradcheck import gradcheck_naive, sanity_check
# Running basic sanity checks
sanity_check()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



### (g). Implement the forward and backward passes for a neural network

In [5]:
from q2_neural import forward_backward_prop, your_sanity_checks
# Running sanity check
sanity_check()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!

